PRAGMA foreign_keys = ON; -- Enable foreign key constraints for SQLite

CREATE TABLE IF NOT EXISTS User (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Login TEXT NOT NULL,
    Password TEXT NOT NULL,
    Email TEXT NOT NULL,
    IsSelected BOOLEAN NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Task (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Description TEXT NOT NULL,
    CreatedDate DATETIME NOT NULL,
    FinishDate DATETIME,
    IsSelected BOOLEAN NOT NULL DEFAULT 0,
    IsDone BOOLEAN NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Pomodoro (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    IsSelected BOOLEAN NOT NULL DEFAULT 0,
    TimeSpent INTEGER NOT NULL,
    Time DATETIME NOT NULL,
    TaskId INTEGER NOT NULL,
    UserId INTEGER NOT NULL,
    FOREIGN KEY (TaskId) REFERENCES Task(Id) ON DELETE CASCADE,
    FOREIGN KEY (UserId) REFERENCES User(Id) ON DELETE CASCADE
);
